main:
    # components_repository: "https://github.com/steelcolosus/ml-devops-build-ml-pipeline-for-short-term-rental-prices#components"
    # All the intermediate files will be copied to this directory at the end of the run.
    # Set this to null if you are running in prod
    project_name: {{cookiecutter.repo_name}}
    experiment_name: {{cookiecutter.experiment_name}}
    steps: all
data_check:
    kl_threshold: 0.2
modeling:
    # Fraction of data to use for test (the remaining will be used for train and validation)
    test_size: 0.2
    # Fraction of remaining data to use for validation
    val_size: 0.2
    # Fix this for reproducibility, change to have new splits
    random_seed: 42
    # Column to use for stratification (use "none" for no stratification)
    stratify_by: "neighbourhood_group"
    # Maximum number of features to consider for the TFIDF applied to the title of the
    # insertion (the column called "name")
